### ISSUE TITLE
README doesn't mention the version requirements of pig

### ISSUE THREAD

**Issue by titsuki** [yahoo/FEL#13]
See: https://issues.apache.org/jira/browse/PIG-4175

As the above post says, PIG CROSS operation follow by STORE produces non-deterministic results and the below portion of codes has the same problem:
https://github.com/yahoo/FEL/blob/master/src/main/pig/compute-graph-alias-entity-counts.pig#L137-L152

I think FEL doesn't run correctly under version 0.12.0 or lower and should require version 0.14.0 or higher.

**Comment by aasish** [comment]
@titsuki Thank you for raising this issue. I will try to make the code v0.14.0 compliant. Please put up a pull request if you have made changes to the code to make it compliant with v0.14.0.

**Comment by titsuki** [comment]
Thanks for your reply !

> if you have made changes to the code to make it compliant with v0.14.0.

I removed the `useHCatalog` flag and made the `mapred.compress.map.output` option `false` when I ran `mine-datapack.sh` on my environment, but I think it's nothing to do with the version of pig.

**Comment by aasish** [comment]
@titsuki  Thank you!
