### ISSUE TITLE
lack of PHRASE.model and PHRASE.model when using CoherentEntityLinker

### ISSUE THREAD

**Issue by freiheitor** [yahoo/FEL#2]
I have read related paper in WSDM2017 and the code. When using the class whose name is
CoherentEntityLinker, the args in the file of README.md are "en/enwiki.wiki2vec.d300.compressed en/english-nov15.hash", I get the wiki2vec and hash files. In fact, there are some other models which are ENTITIES.PHRASE.model and PHRASE.model to load. Would you please provide those ENTITIES.PHRASE.model and PHRASE.model in language of English and Chinese?

**Comment by aasish** [comment]
Thanks @freiheitor  for reporting this issue. We will update the code base that wouldn't require to use these additional models. These models were part of experimentation but didn't show  improvement, therefore we omitted them from distribution.

**Comment by aasish** [comment]
@freiheitor Please use CoherentEntityLinkerWrapper class on list of named entities (as shown in example in README) with hash file and wiki2vec.

**Comment by freiheitor** [comment]
Thank you very much.
