### ISSUE TITLE
about the model

### ISSUE THREAD

**Issue by aurora5161** [yahoo/FEL#3]
Dear author：
     Thank you for your contribution. I use the chinese hash model to get the entities using com.yahoo.semsearch.fastlinking.FastEntityLinker class and get results. However，the result is not good enough. Could you do me a favor to improve the model？I have two questions to ask:1.Is the result related to the hash model？2.can I train model using my own data？ Thank you very much!

**Comment by aasish** [comment]
Dear @aurora5161  
Yes, you can train a model following the instructions provided here:

https://github.com/yahoo/FEL/tree/master/src/main/java/com/yahoo/semsearch/fastlinking/io
