### ISSUE TITLE
I have not find the class CoherentEntityLinkerWrapper

### ISSUE THREAD

**Issue by liuyichaosoftware** [yahoo/FEL#4]
Dear Author,

_mvn clean compile  exec:java -Dexec.mainClass=com.yahoo.semsearch.fastlinking.CoherentEntityLinkerWrapper -Dexec.args="en/enwiki.wiki2vec.d300.compressed en/english-nov15.hash test.txt"  -Dexec.classpathScope=compile_

when I exec the command, I find there is no class named CoherentEntityLinkerWrapper.
I downloaded your model english-nov15.hash and enwiki.wiki2vec.d300.compressed, but I can't find Entity file. How can I use EntityContextFastEntityLinker with your trained model?

thank you~

**Comment by aasish** [comment]
@liuyichaosoftware 
Please do a git pull on the master branch and run `mvn clean install`

Here's the class:
`https://github.com/yahoo/FEL/blob/master/src/main/java/com/yahoo/semsearch/fastlinking/CoherentEntityLinkerWrapper.java`

**Comment by liuyichaosoftware** [comment]
thank you@ aasish
