### ISSUE TITLE
class not found error

### ISSUE THREAD

**Issue by zphuangHKUCS** [yahoo/FEL#5]
Dear Authors,

When I try to run your tool, I encounter a "java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/io/BinIO".

I found that the codes for this class is missing in your github. I wonder if I use the wrong commands to compile the project. (mvn compile)

Regards,
zphuang

**Comment by aasish** [comment]
Can you make sure you ran `mvn install package` and following dependency (`fastutil`) is present in your local mvn repository. 

`
            <dependency>
			<groupId>it.unimi.dsi</groupId>
			<artifactId>fastutil</artifactId>
			<version>6.5.12</version>
		</dependency> 
`

**Comment by zphuangHKUCS** [comment]
Thanks for your reply!

After I ran mvn install package, I got a new folder named "target", under which I can see the following:

![1](https://cloud.githubusercontent.com/assets/18510926/21757946/f6a7c58a-d670-11e6-94e6-71d996aeb096.png)


Then, I cd into folder "classes", and ran
 "java -Xmx10G com.yahoo.semsearch.fastlinking.FastEntityLinker --help"
, and got the following error:

![2](https://cloud.githubusercontent.com/assets/18510926/21757950/fc2acc1e-d670-11e6-861d-0b26518ec420.png)


I wonder whether I ran the project wrongly. Thanks a lot!

**Comment by aasish** [comment]
Please run the command in the project's working directory i.e., ~/zphuang/git/FEL

**Comment by zphuangHKUCS** [comment]
Thanks for your reply. Even though I run the command in the working directory, the same error happens. I am afraid that I have not downloaded the dependencies. The following pic shows the target folder.

![image](https://cloud.githubusercontent.com/assets/18510926/22055331/a4d64282-dd95-11e6-9dc1-408e36ae2bf8.png)

Is it normal that we only have two .jar files?

**Comment by aasish** [comment]
@zphuangHKUCS  Can you try following command

`mvn clean compile  exec:java -Dexec.mainClass=com.yahoo.semsearch.fastlinking.FastEntityLinker Dexec.args=" en/english-nov15.hash"  -Dexec.classpathScope=compile`

**Comment by zphuangHKUCS** [comment]
Thanks for your reply. But I still encounter an error:

[ERROR] Unknown lifecycle phase "Dexec.args= en/english-nov15.hash". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]

**Comment by ArthurCamara** [comment]
Anything new on this issue? @zphuangHKUCS @aasish

**Comment by emilioalvarado** [comment]
I'm dissapointed for not find a solution for these basic problems, I tried a lot of ways in order to run the FEL project but it was not possible. I hoped a basic runnable example, more if coming from Yahoo team. 
For Entity Identification, I recommend the Stanford project (https://nlp.stanford.edu/software/CRF-NER.shtml). They have a clear explanation, working examples and an online demo (http://nlp.stanford.edu:8080/ner/process).

**Comment by aasish** [comment]
@zphuangHKUCS @ArthurCamara @emilioalvarado 
The error mentioned in @zphuangHKUCS's latest comment is due to missing hyphen in Dexec.args. 
This project requires a valid Maven installation as a dependency (as listed in the README).
