### ISSUE TITLE
about EntityEmbeddings -files parameter

### ISSUE THREAD

**Issue by hitxujian** [yahoo/FEL#6]
hello:
i want to do some entity embedding,with below command,but i don't know the paramter --files?
"
hadoop jar FEL-0.1.0-fat.jar com.yahoo.semsearch.fastlinking.w2v.EntityEmbeddings  -Dmapreduce.job.queuename=adhoc -files word_vectors#vectors E2W entity.embeddings
"
i think it may the input or output of word embedding command,but not
"
java com.yahoo.semsearch.fastlinking.w2v.Quantizer -i <word_embeddings> -o <output> -h
"
can you give me some suggestions? thanks

**Comment by roiblanco** [comment]
The instructions to create the embeddings are detailed here:
https://github.com/yahoo/FEL/blob/master/src/main/java/com/yahoo/semsearch/fastlinking/w2v/README.md

In particular that class runs on hadoop and requires the compressed word embeddings and the entity descriptions file, which can be generated from Wikipedia using com.yahoo.semsearch.fastlinking.utils.ExtractFirstParagraphs

If you don't have access to a hadoop cluster the EntityEmbeddings class has a single machine standalone method that you can use.
