### ISSUE TITLE
How could we link the Entity Candidates to their Surface From in query?

### ISSUE THREAD

**Issue by yuchenlin** [yahoo/FEL#7]
Hey, Dear aasish:

I am very curious about how to link the candidates in the result list into their surface form.

Now, my stand-alone result is like:
`>Trump had dinner with me tonight.

Trump had dinner with me tonight.		Donald_Trump	-3.6968905396651404	1331552

Trump had dinner with me tonight.		Dinner	-3.811408020070193	1300672

Trump had dinner with me tonight.		Come_Dine_with_Me	-3.871200967594029	1082062
.......`

However, it seems that we cannot get the surface form of Donald_Trump directly in your code. In another word, could I get the output like this: 
`Trump(Donald_Trump) had dinner with me tonight.`
?
If it is possible, this would be very helpful for our research.
Thank you very much in advance.

**Comment by aasish** [comment]
@yuchenlin 

If you call the following method `getResults` in the following class, you would see `EntityResult` object being returned. `EntityResult` has a field named `Span` which can give you offset with respect to the input text.


https://github.com/yahoo/FEL/blob/master/src/main/java/com/yahoo/semsearch/fastlinking/FastEntityLinker.java#L123

**Comment by ArthurCamara** [comment]
I was about to ask that. Thanks!

**Comment by aasish** [comment]
@ArthurCamara

**Comment by ArthurCamara** [comment]
A quick follow-up: I'm wondering if it's possible to do the same for coherentEntityLinker. Here is what i'm currently at:

changed EntityResult to add a Span variable
including variable in the map as such:
```
List<EntityResult> candidates = felCandidates.stream().map(felResult -> {
        String wikiId = ...;
        return new EntityResult(wikiId, felResult.score, felResult.type, felResult.s);
```

but the Span variable seems to hold the entire query, instead of only the surface form. Is it the expected behaviour? Or is there a step I'm missing?

Thanks!
